from typing import List, Dict, Any

NEWS_SOURCES: List[Dict[str, Any]] = [
    # --- CHUYÊN MỤC: TRÍ TUỆ NHÂN TẠO (AI) & CÔNG NGHỆ CHUYÊN SÂU ---
    {
        "id": "vnexpress_ai",
        "name": "VnExpress AI",
        "domain": "vnexpress.net",
        "url": "https://vnexpress.net/rss/ai.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.6,
    },
    {
        "id": "vietnamnet_ai",
        "name": "VietnamNet Công Nghệ & AI",
        "domain": "vietnamnet.vn",
        "url": "https://vietnamnet.vn/rss/thong-tin-truyen-thong.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.5,
    },
    {
        "id": "venturebeat_ai",
        "name": "VentureBeat AI",
        "domain": "venturebeat.com",
        "url": "https://venturebeat.com/category/ai/feed/",
        "region": "world",
        "category": "tech_world",
        "tier": 1.6,
    },
    {
        "id": "mit_tech_ai",
        "name": "MIT Technology Review AI",
        "domain": "technologyreview.com",
        "url": "https://www.technologyreview.com/feed/",
        "region": "world",
        "category": "tech_world",
        "tier": 1.6,
    },
    {
        "id": "techcrunch_ai",
        "name": "TechCrunch AI",
        "domain": "techcrunch.com",
        "url": "https://techcrunch.com/category/artificial-intelligence/feed/",
        "region": "world",
        "category": "tech_world",
        "tier": 1.6,
    },
    {
        "id": "openai_news",
        "name": "OpenAI News & Research",
        "domain": "openai.com",
        "url": "https://openai.com/news/rss.xml",
        "region": "world",
        "category": "tech_world",
        "tier": 1.7,
    },
    {
        "id": "arstechnica_techlab",
        "name": "Ars Technica Tech & AI",
        "domain": "arstechnica.com",
        "url": "https://feeds.arstechnica.com/arstechnica/technology-lab",
        "region": "world",
        "category": "tech_world",
        "tier": 1.5,
    },

    # --- VIỆT NAM: CÔNG NGHỆ & SỐ HÓA ---
    {
        "id": "vnexpress_sohoa",
        "name": "VnExpress Khoa Học & Tech",
        "domain": "vnexpress.net",
        "url": "https://vnexpress.net/rss/khoa-hoc-cong-nghe.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.5,
    },
    {
        "id": "tuoitre_khoahoc",
        "name": "Tuổi Trẻ Khoa Học & Tech",
        "domain": "tuoitre.vn",
        "url": "https://tuoitre.vn/rss/khoa-hoc.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.4,
    },
    {
        "id": "genk_tech",
        "name": "GenK Công Nghệ",
        "domain": "genk.vn",
        "url": "https://genk.vn/index.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.4,
    },
    {
        "id": "tinhte_feed",
        "name": "Tinh Tế",
        "domain": "tinhte.vn",
        "url": "https://tinhte.vn/rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.3,
    },
    {
        "id": "dantri_sucmanhso",
        "name": "Dân Trí Sức Mạnh Số",
        "domain": "dantri.com.vn",
        "url": "https://dantri.com.vn/rss/suc-manh-so.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.3,
    },
    {
        "id": "vietnamnet_tech",
        "name": "VietnamNet Công Nghệ",
        "domain": "vietnamnet.vn",
        "url": "https://vietnamnet.vn/cong-nghe.rss",
        "region": "vietnam",
        "category": "tech_vn",
        "tier": 1.3,
    },

    # --- THẾ GIỚI: CÔNG NGHỆ (TECH WORLD) ---
    {
        "id": "theverge_tech",
        "name": "The Verge",
        "domain": "theverge.com",
        "url": "https://www.theverge.com/rss/index.xml",
        "region": "world",
        "category": "tech_world",
        "tier": 1.5,
    },
    {
        "id": "techcrunch_feed",
        "name": "TechCrunch",
        "domain": "techcrunch.com",
        "url": "https://techcrunch.com/feed/",
        "region": "world",
        "category": "tech_world",
        "tier": 1.5,
    },
    {
        "id": "wired_tech",
        "name": "Wired",
        "domain": "wired.com",
        "url": "https://www.wired.com/feed/rss",
        "region": "world",
        "category": "tech_world",
        "tier": 1.4,
    },
    {
        "id": "hackernews_rss",
        "name": "Hacker News",
        "domain": "news.ycombinator.com",
        "url": "https://hnrss.org/frontpage",
        "region": "world",
        "category": "tech_world",
        "tier": 1.4,
    },

    # --- VIỆT NAM: TIN NÓNG THỜI SỰ TRONG NGÀY ---
    {
        "id": "vnexpress_tinmoi",
        "name": "VnExpress Tin Mới",
        "domain": "vnexpress.net",
        "url": "https://vnexpress.net/rss/tin-moi-nhat.rss",
        "region": "vietnam",
        "category": "hot_vn",
        "tier": 1.5,
    },
    {
        "id": "vnexpress_thoisu",
        "name": "VnExpress Thời Sự",
        "domain": "vnexpress.net",
        "url": "https://vnexpress.net/rss/thoi-su.rss",
        "region": "vietnam",
        "category": "hot_vn",
        "tier": 1.5,
    },
    {
        "id": "tuoitre_tinmoi",
        "name": "Tuổi Trẻ Tin Mới",
        "domain": "tuoitre.vn",
        "url": "https://tuoitre.vn/home.rss",
        "region": "vietnam",
        "category": "hot_vn",
        "tier": 1.4,
    },
    {
        "id": "dantri_sukien",
        "name": "Dân Trí Sự Kiện",
        "domain": "dantri.com.vn",
        "url": "https://dantri.com.vn/rss/su-kien.rss",
        "region": "vietnam",
        "category": "hot_vn",
        "tier": 1.3,
    },
]
